services:
    db: 
        container_name: dbwordpress
        image: mariadb:10.5
        restart: always
        volumes:
            - /opt/compose/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: cvdfer34
            MYSQL_DATABASE: bdwordpress
            MYSQL_USER: juantrucupei
            MYSQL_PASSWORD: cvdfer34.
        networks:
            - wordpress-net
    wordpress:
        container_name: wordpress
        image: wordpress:latest
        depends_on:
            - db
        volumes:
            - /opt/compose/wordpress:/var/www/html
	    - /opt/compose/php/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            WORDPRESS_DB_NAME: bdwordpress
            WORDPRESS_DB_USER: juantrucupei
            WORDPRESS_DB_PASSWORD: cvdfer34
            - WORDPRESS_DB_HOST: db
        ports:
            - 82:80
        networks:
            - wordpress-net
        links:
            - db
networks:
    wordpress-net:
        driver:bridge
